### ISSUE TITLE
Person.name instead of given- & familyName?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/coldp#34]
ColDP uses givenName and familyName for persons in the [metadata.yaml](https://github.com/CatalogueOfLife/coldp/blob/master/metadata.yaml#L22).

This follows [W3C recommendations](https://www.w3.org/International/questions/qa-personal-names.en) not to use first/lastname to capture names in different locales. It also fits with [ORCIDs data model](https://pub.orcid.org/v3.0/#!/Development_Public_API_v3.0/viewRecordv3), that also returns givenNames (plural!) and a familyName when resolving an identifier.

But there is an even more simple solution to just use a single `name` property instead, which is the first W3C recommendation and also what the People Task Group in TDWG decided to use.

given/familyName does allow to abbreviate names and format them differently when used in citations - which is an important use for person metadata.

Is it reasonable to stick with given & family name?
Should we allow multiple given names or is it fine to put several given names into the single property as we do now?

**Comment by mjy** [comment]
Completely dependend on what your use cases are.  If your use cases are to build citations then I suggest you use the BibTeX format, 4 fields, and rely solely on BibTeX for rendering descisions.  last_name, first_name, suffix, prefix.  Note that that is not Orcids use case.

Names are a nightmare, nothing will work for everything, and trying to make up your own standard is highly unrewarding.

**Comment by mdoering** [comment]
First- and lastname is rather old school and not applicable to many non western locales. It is not recommended these days (see links above). The choice is not our own standard, but rather the format in use by ORCID and recommended by W3C or a simple, single string.

**Comment by mjy** [comment]
A simple single string is fantastic and very good way to do it, I completely recommend not having to ever think about citing things in styles.  The community will have to be OK with not being able to do "Smith, 1920", say on a web page.  I.E. good luck with rendering citations in any CSL format though.   You'll still have to break it down, into pieces, and do stuff.

Call the fields whatever you want, you might be getting caught up on the labels rather than the meaning. If you look at what BibTeX is doing it's a "before" (first), and "after" (pre, last, suffix).    You can put as many words, in combination with abbreviations any of those slots, and chances are the CSL will render beautifully.

We've found issues for sure, but the benefits have far outweighed the problems .

**Comment by mjy** [comment]
Last bit- the W3 standard is rife with use case information, that's really all. 

* If you want to create a reasonable bibliography tool, you're going to have to split fields 
* If you want to display names on a page for in a metadata context for some dataset, or provider, just use 1 name
* ORCIDs use case is the latter, not the former

So- you can answer the question by identifying your use case(s) :)
